#!/usr/bin/env bash

set -Eeuo pipefail

mkdir -p .dev

pnpm build:latex

rm -rf ../effect-ts-laws-docs/*

typedoc --options config/typedoc.json

cp -r docs/status.html \
      docs/catalog-of-laws.html \
      docs/catalog \
      docs/resources \
      ../effect-ts-laws-docs
