#!/usr/bin/env bash

set -Eeuo pipefail

cd src/arbitrary/docs

for file in *.api.tex; do
  base=${file%.api.tex}
  latexmk -cd -output-format=dvi -dvi -rc-report- $file
  dvisvgm --bbox=min --exact-bbox --exact --optimize=all --precision=2 \
          --scale=1.25 --relative --no-fonts --verbosity=2 \
          --output=$base.svg $base.api.dvi
  rm -f *.aux *.log *.dvi *.fls *.out *.fdb_latexmk *.pdf
done
