#!/usr/bin/env bash

set -Eeuo pipefail

mkdir -p .dev

rm -rf ../effect-ts-laws-docs/*

pnpm coverage

typedoc --options config/typedoc.json

cp -r docs/status.html \
      docs/catalog-of-laws.html \
      docs/catalog \
      docs/resources \
      ../effect-ts-laws-docs

cp -r .dev/coverage ../effect-ts-laws-docs
