#!/usr/bin/env bash

path="${1:-src}"
output="${2:-dot}"
config="--config config/dependency-cruiser.cjs"
out=".dev/dependency-graph.svg"

EXE='./node_modules/.bin/depcruise'

[ -d .dev ] || mkdir .dev

[[ $(type -P dot) ]] ||
  echo 'Cannot find dot, install at: https://graphviz.org/download/'

[[ $(type -P d2) ]] ||
  echo 'Cannot find d2, install at: https://d2lang.com/tour/install/'

if [[ "$output" =~ ^.*dot$ ]]; then
  $EXE "$path" \
       $config \
       --output-type "$output" | dot -T svg | 
       sed 's/stroke-width="2"/stroke-width="0.8"/g' > \
       "$out"
elif [[ "$output" = "dagre" ]]; then
  $EXE "$path" \
       $config \
       --output-type d2 | d2 --layout dagre --scale 1 - > \
       "$out"
else
  $EXE "$path" \
       $config \
       --output-type d2 | d2 --layout elk --scale 1 - > \
       "$out"
fi


