#!/usr/bin/env bash

set -Eeuo pipefail

pnpm clean
pnpm lint
pnpm test-run

pnpm build-docs
cp docs/catalog-of-laws.html ../effect-ts-laws-docs
cd ../effect-ts-laws-docs
git add .
git commit -m publish
git push
cd ../effect-ts-laws

pnpm build
mkdir -p .dev/dist
mv dist/* .dev/dist
cp package.json .dev/dist
cp .npmrc .dev/dist
cd .dev/dist
perl -pi -E 's/^ *"test":.*\n//mg' package.json
pnpm install
pnpm publish 
