#!/usr/bin/env bash

set -Eeuo pipefail

pnpm clean
pnpm lint
pnpm typecheck
pnpm run:examples
pnpm circular
pnpm test:run
pnpm build
pnpm build:demo
pnpm build:tests

cp package.json .dev/dist
cp package.json .dev/demo
cp package.json .dev/test
