#!/usr/bin/env bash

set -Eeuo pipefail

# Until docgen does not depend on doctrine which depends on lodash
# cp config/docgen.json .
# pnpm docgen

# rm docgen.json docs/_config.yml docs/index.md docs/modules/index.md

